public enum FilterOptions {

    SEATS_AVAILABLE,
    FIRST_CLASS,
    BUISNESS_CLASS,
    ECONOMY,
    DEPARTURE_EVENING,
    DEPARTURE_AFTERNOON,
    DEPARTURE_MORNING,
    ARRIVAL_MORNING,
    ARRIVAL_AFTERNOON,
    ARRIVAL_EVENING,
    CONNECTING_FLIGHTS
}
